const mongoose = require('mongoose');

/**
 * LOOOP Impact Event Schema
 * Records the immutable, verifiable environmental impact generated by a completed transaction.
 *
 * CRITICAL BUSINESS RULES:
 * 1. Only COMPLETED transactions can generate an ImpactEvent.
 * 2. Idempotent: Unique index on transaction guarantees no double-counting.
 * 3. Metrics are strictly populated from configured ImpactFactors. If a factor is unavailable,
 *    the metric remains null (indicating unavailable, not 0 kg).
 * 4. Preserves historical factor/methodology snapshots so changes to factors do not rewrite history.
 */
const impactItemSchema = new mongoose.Schema(
  {
    itemId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Item',
      required: true
    },
    title: {
      type: String,
      trim: true,
      default: ''
    },
    category: {
      type: String,
      trim: true,
      default: 'Other'
    },
    quantity: {
      type: Number,
      default: 1,
      min: 1
    },
    factorsApplied: [
      {
        factorId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'ImpactFactor'
        },
        metricType: {
          type: String,
          enum: ['CO2E_AVOIDED', 'WASTE_AVOIDED', 'WATER_SAVED', 'REUSE_COUNT']
        },
        factorValue: {
          type: Number
        },
        unit: {
          type: String
        },
        basis: {
          type: String
        },
        source: {
          type: String
        },
        calculatedValue: {
          type: Number
        }
      }
    ]
  },
  { _id: false }
);

const impactEventSchema = new mongoose.Schema(
  {
    transaction: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Transaction',
      required: [true, 'Impact event must be linked to a transaction'],
      unique: true,
      index: true
    },
    ownerUser: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Item owner is required for attribution'],
      index: true
    },
    recipientUser: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Recipient is required for attribution'],
      index: true
    },
    impactType: {
      type: String,
      required: [true, 'Impact type is required'],
      enum: ['FREE', 'GIVEAWAY', 'BORROW', 'EXCHANGE'],
      index: true
    },
    category: {
      type: String,
      trim: true,
      default: 'Other',
      index: true
    },
    quantity: {
      type: Number,
      default: 1,
      min: 1
    },
    items: {
      type: [impactItemSchema],
      default: []
    },
    metrics: {
      reuseCount: {
        type: Number,
        default: 1,
        min: 1
      },
      estimatedCo2eAvoided: {
        type: Number,
        default: null // kg CO2e; null if unconfigured
      },
      estimatedWasteAvoided: {
        type: Number,
        default: null // kg waste; null if unconfigured
      },
      estimatedWaterSaved: {
        type: Number,
        default: null // liters; null if unconfigured
      }
    },
    methodologyVersion: {
      type: String,
      trim: true,
      default: '1.0'
    },
    factorVersion: {
      type: String,
      trim: true,
      default: '1.0'
    },
    source: {
      type: String,
      trim: true,
      default: 'Platform verified impact factors'
    },
    calculationNotes: {
      type: String,
      trim: true,
      default: ''
    }
  },
  {
    timestamps: true
  }
);

// Indexes for query performance
impactEventSchema.index({ ownerUser: 1, createdAt: -1 });
impactEventSchema.index({ recipientUser: 1, createdAt: -1 });
impactEventSchema.index({ category: 1, createdAt: -1 });
impactEventSchema.index({ createdAt: -1 });

module.exports = mongoose.model('ImpactEvent', impactEventSchema);
