const mongoose = require('mongoose');

/**
 * LOOOP Notification Schema
 * Represents authoritative, database-backed activity alerts and notifications
 * generated by real platform lifecycle events.
 */
const notificationSchema = new mongoose.Schema(
  {
    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Notification must have a recipient'],
      index: true
    },
    actor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null
    },
    type: {
      type: String,
      required: [true, 'Notification type is required'],
      enum: {
        values: [
          'REQUEST_RECEIVED',
          'REQUEST_ACCEPTED',
          'REQUEST_DECLINED',
          'REQUEST_CANCELLED',
          'TRANSACTION_CREATED',
          'HANDOVER_SCHEDULED',
          'HANDOVER_CONFIRMED',
          'RETURN_STARTED',
          'RETURN_CONFIRMED',
          'TRANSACTION_COMPLETED',
          'NEW_MESSAGE',
          'WANTED_MATCH',
          'WANTED_RESPONSE',
          'ITEM_UPDATED',
          'ITEM_UNAVAILABLE',
          'REPORT_UPDATE',
          'SECURITY_ALERT',
          'IMPACT_MILESTONE',
          'REVIEW_RECEIVED'
        ],
        message: 'Invalid notification type'
      }
    },
    category: {
      type: String,
      required: [true, 'Notification category is required'],
      enum: {
        values: [
          'REQUESTS',
          'TRANSACTIONS',
          'MESSAGES',
          'MATCHING',
          'ITEMS',
          'SAFETY',
          'ACCOUNT',
          'IMPACT',
          'SYSTEM'
        ],
        message: 'Invalid notification category'
      },
      index: true
    },
    title: {
      type: String,
      required: [true, 'Notification title is required'],
      trim: true
    },
    message: {
      type: String,
      required: [true, 'Notification message is required'],
      trim: true,
      maxlength: [1000, 'Notification message cannot exceed 1000 characters']
    },
    link: {
      type: String,
      default: null
    },
    dedupeKey: {
      type: String,
      default: null,
      index: true
    },
    relatedEntityType: {
      type: String,
      enum: ['Request', 'Transaction', 'Conversation', 'Item', 'WantedItem', 'User', 'Review', 'Impact', null],
      default: null
    },
    relatedEntityId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null
    },
    relatedItem: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Item',
      default: null
    },
    relatedWantedItem: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'WantedItem',
      default: null
    },
    relatedRequest: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Request',
      default: null
    },
    relatedTransaction: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Transaction',
      default: null
    },
    relatedConversation: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Conversation',
      default: null
    },
    isRead: {
      type: Boolean,
      default: false,
      index: true
    },
    readAt: {
      type: Date,
      default: null
    },
    deletedAt: {
      type: Date,
      default: null,
      index: true
    }
  },
  {
    timestamps: true
  }
);

// Compound indexes for user notification feeds, unread filtering, and deduplication
notificationSchema.index({ recipient: 1, deletedAt: 1, createdAt: -1 });
notificationSchema.index({ recipient: 1, deletedAt: 1, isRead: 1, createdAt: -1 });
notificationSchema.index({ recipient: 1, deletedAt: 1, category: 1, createdAt: -1 });
notificationSchema.index({ recipient: 1, dedupeKey: 1 });
notificationSchema.index({ recipient: 1, type: 1, relatedEntityId: 1 });

module.exports = mongoose.model('Notification', notificationSchema);
