import api from './api';

/**
 * LOOOP Environmental Impact Service
 * Provides frontend consumption of real, deterministic impact calculations
 * generated by completed reuse transactions on the backend.
 *
 * NOTE: Never hardcodes fake scientific conversion metrics.
 */
export const impactService = {
  // 1. Get authenticated user's real impact summary
  getMyImpact: async () => {
    const response = await api.get('/impact/me');
    return response.data;
  },

  // Backward-compatible alias for getMyImpact
  getImpactMetrics: async () => {
    const response = await api.get('/impact/me');
    return response.data;
  },

  // 2. Get authenticated user's paginated impact history
  getMyImpactHistory: async (params = {}) => {
    const response = await api.get('/impact/me/history', { params });
    return response.data;
  },

  // 3. Get authenticated user's real activity trends
  getMyImpactTrends: async (params = {}) => {
    const response = await api.get('/impact/me/trends', { params });
    return response.data;
  },

  // 4. Public platform-wide sustainability summary
  getImpactSummary: async () => {
    const response = await api.get('/impact/summary');
    return response.data;
  },

  // 5. Public user impact summary (for public profile)
  getUserPublicImpact: async (userId) => {
    const response = await api.get(`/impact/user/${userId}`);
    return response.data;
  },

  // 6. Admin platform impact summary
  getAdminImpactSummary: async () => {
    const response = await api.get('/admin/impact/summary');
    return response.data;
  },

  // 7. Admin platform trends
  getAdminImpactTrends: async (params = {}) => {
    const response = await api.get('/admin/impact/trends', { params });
    return response.data;
  },

  // 8. Admin get all configured impact factors
  getImpactFactors: async () => {
    const response = await api.get('/admin/impact/factors');
    return response.data;
  },

  // 9. Admin create impact factor
  createImpactFactor: async (factorData) => {
    const response = await api.post('/admin/impact/factors', factorData);
    return response.data;
  },

  // 10. Admin update impact factor
  updateImpactFactor: async (id, factorData) => {
    const response = await api.patch(`/admin/impact/factors/${id}`, factorData);
    return response.data;
  },

  // 11. Admin deactivate / delete impact factor
  deleteImpactFactor: async (id) => {
    const response = await api.delete(`/admin/impact/factors/${id}`);
    return response.data;
  },

  // 12. Admin recalculate impact for a transaction
  recalculateTransactionImpact: async (transactionId, reason = '') => {
    const response = await api.post(`/admin/impact/recalculate/${transactionId}`, { reason });
    return response.data;
  }
};

export default impactService;
